import { expect, it } from "vite-plus/test";
import { attachmentDocumentPresentation } from "./attachmentDocumentPresentation";

it.each([
  {
    kind: "markdown",
    isSvg: false,
    hasTable: false,
    hasEnvironment: false,
    rendered: true,
    renderedMode: null,
    activeMode: "source",
  },
  {
    kind: "markdown",
    isSvg: false,
    hasTable: false,
    hasEnvironment: true,
    rendered: true,
    renderedMode: "markdown",
    activeMode: "markdown",
  },
  {
    kind: "markdown",
    isSvg: false,
    hasTable: false,
    hasEnvironment: true,
    rendered: false,
    renderedMode: "markdown",
    activeMode: "source",
  },
  {
    kind: "text",
    isSvg: false,
    hasTable: false,
    hasEnvironment: true,
    rendered: true,
    renderedMode: null,
    activeMode: "source",
  },
  {
    kind: "text",
    isSvg: false,
    hasTable: true,
    hasEnvironment: false,
    rendered: true,
    renderedMode: "table",
    activeMode: "table",
  },
  {
    kind: "text",
    isSvg: false,
    hasTable: true,
    hasEnvironment: true,
    rendered: false,
    renderedMode: "table",
    activeMode: "source",
  },
  {
    kind: "html",
    isSvg: false,
    hasTable: false,
    hasEnvironment: false,
    rendered: true,
    renderedMode: "html",
    activeMode: "html",
  },
  {
    kind: "html",
    isSvg: false,
    hasTable: false,
    hasEnvironment: true,
    rendered: false,
    renderedMode: "html",
    activeMode: "source",
  },
  {
    kind: "image",
    isSvg: true,
    hasTable: false,
    hasEnvironment: false,
    rendered: true,
    renderedMode: "svg",
    activeMode: "svg",
  },
  {
    kind: "image",
    isSvg: true,
    hasTable: false,
    hasEnvironment: true,
    rendered: false,
    renderedMode: "svg",
    activeMode: "source",
  },
  {
    kind: "image",
    isSvg: false,
    hasTable: false,
    hasEnvironment: true,
    rendered: true,
    renderedMode: null,
    activeMode: "source",
  },
] as const)("matches the available preview for %j", ({ renderedMode, activeMode, ...input }) => {
  expect(attachmentDocumentPresentation(input)).toEqual({ renderedMode, activeMode });
});
